version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: big-tim_server_1
      APP_PORT: 8000
    
  server:
    image: arthurrrrrr/bigtim
    user: "1000:1000"
    init: true
